version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "expense-receipts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1etr0kdn80b3u"
s3_prefix = "enter-receipts"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
